### ISSUE TITLE
DRIFT_LIMIT in reverse_purge_hash_map

### ISSUE THREAD

**Issue by weyrick** [apache/incubator-datasketches-cpp#110]
Hi, thanks for your work on this library!

I've begun testing the frequent item sketch, and I'm hitting the `drift limit reached` exception in `reverse_purge_hash_map` under production data streams. The comment indicates `used only for stress testing` but it throws a `std::logic_error`. I tried doubling the limit to 2048 but still see this exception (less frequently), and I'd like to not have to adjust this value locally in my code base.

Can you discuss the significance of this and how to address? The "drift" tracking seems to indicate hash collisions but I'm not sure of the best way forward.

**Comment by leerho** [comment]
Hi, thanks for posting this.  You should not have to adjust this value.  The fact that this is showing up at all indicates an internal problem in the sketch.  What can cause this is rather complex but this error indicates that the merging process is not sufficiently randomizing the values going into the hash_map causing the hash-map to build clusters that get too big.  More than likely this is also seriously impacting your merge speed performance.  We will look at this right away but we could use your help.    

1. What version of the code are you using? Are you calling directly from C++ or using Python?
2. What size sketch(s) are you using? 
3. Can you give us some since of the data volumes:  Roughly how many sketches are involved in this operation? How many updates / merges are typically involved?  And what is the item data type?
4. Also, and I realize this may be difficult, but if you can recreate this problem using synthetic data, where we could reproduce the problem that would be ideal.

We will get back to you for sure on Monday.

**Comment by leerho** [comment]
@weyrick 
5.  Are you supplying your own hash function?  
6.  What does your call template look like?
7.  Have you modified the sketch code in any way?

We are waiting to hear from you.  :)

**Comment by weyrick** [comment]
@leerho thanks for the quick response!

Context is, this is passive network analysis. The sketch that is hitting the drift limit is IPv4 addresses, so `uint32_t` type.

1. Code is all C++
2. Start size is 7, max is 13 though i played with a

**Comment by AlexanderSaydakov** [comment]
1. What is the version? Are you using the latest code from master or some other version?
6. Could you show your template instantiation please?
Thank you.

**Comment by weyrick** [comment]
1. I just updated to the latest code, but I haven't verified the drift problem with it yet. I'm having a hard time identifying the version used in my previous internal release - it was copied into code base a few months ago. Is there a file that identifies an explicit version? Our fork is here https://github.com/nsone/incubator-datasketches-cpp .. but as I said, I just yesterday merged upstream and I'm not sure what exact commit it was at previously.
2. Is this what you're looking for?
```
struct IPv4Hash {
    size_t operator()(uint32_t k) {
        return pcpp::fnv_hash((uint8_t*)&k, sizeof(k));
    }
};
...
    const uint8_t START_FI_MAP_SIZE = 7;  // 2^7 = 128
    const uint8_t MAX_FI_MAP_SIZE = 13; // 2^13 = 8192
...
    datasketches::frequent_items_sketch<uint32_t, uint64_t, IPv4Hash> _net_topIPv4;
...
        , _net_topIPv4(MAX_FI_MAP_SIZE, START_FI_MAP_SIZE)
...
```

**Comment by AlexanderSaydakov** [comment]
Thanks, this is what I was looking for.
So what was wrong with the default std::hash<uint32_t>? Same drift problem or something else?

**Comment by AlexanderSaydakov** [comment]
Just to make sure the hash is not a problem, I would suggest trying this great hash function. It is defined for 64-bit type, but you can call it for 32-bit type as well.

`// This hash function is taken from the internals of Austin Appleby's MurmurHash3 algorithm
struct hash_long_long {
  size_t operator()(long long key) const {
    key ^= key >> 33;
    key *= 0xff51afd7ed558ccdL;
    key ^= key >> 33;
    key *= 0xc4ceb9fe1a85ec53L;
    key ^= key >> 33;
    return key;
  }
};
`

**Comment by weyrick** [comment]
Yes, we first saw the problem with `std::hash<uint32_t>`. Switching to fnv reduced frequency by quite a bit, but it still showed up. Finally I tried doubling the DRIFT_LIMIT to 2048, which solved _most_ drift exceptions in our limited canary testing, but we were still seeing them so I would expect an unacceptable rate at full scale.

I will try that hash function, thanks.

**Comment by leerho** [comment]
Unfortunately, the fnv hash is not known for good mixing and fails avalanche tests.  Hopefully, the hash that Alex is suggesting might be better.

Are your IPv4 addresses typically from just a few subnets?

**Comment by weyrick** [comment]
So I do have one local test case that reproduces the drift issue. It's not in a form that I can easily share at the moment, but I can confirm that the latest version of the sketch code plus the hash function you shared above does fix it. Unfortunately, that doesn't prove very much because so did the fnv hash version. So I won't know for sure until I get it into some more production flow testing.

**Comment by weyrick** [comment]
We'll be testing this with production data streams, I'll update this thread once I know more.

**Comment by AlexanderSaydakov** [comment]
We implemented additional mixing of the output from the given hash function (just like we did in Java already), so now, probably, even the default std::hash<uint32_t> should work fine

**Comment by weyrick** [comment]
Great! We've run this pretty successfully with some production data streams now, I think we can close this issue. If it resurfaces, I will reopen. Thanks again for your help on this.
