### ISSUE TITLE
Lack of cross-validation testing between C++, Java

### ISSUE THREAD

**Issue by leerho** [apache/incubator-datasketches-cpp#150]
Issue #149 would have been easily discovered if we had cross-validation testing between Java and C++.   This is a critical bug against the release process.   To clear this bug I am suggesting that we can demonstrate:

- An automated or semi-automated cron job that can be easily extended.  This job would run tests in java and C++, that produce binary results that can be directly compared without having to resort to static stored binaries.

- This job should be run at least nightly, and run against any Release Candidate.

The qualifications required to clear this bug are certainly open for discussion.

**Comment by jmalkin** [comment]
We either need to perform such tests out of characterization or create a dedicated repo to handle that. Please either create the issue against a more appropriate repository or as a JIRA ticket. IT is also an enhancement rather than a bug.
