### ISSUE TITLE
Remove c-style const casts in kll/ and common/ directories

### ISSUE THREAD

**Issue by gaborkaszab** [apache/incubator-datasketches-cpp#165]
I recently started integrating the Apache DataSketches C++ library into Apache Impala and our build system (with clang tidy) found some casts where the const-ness is casted away using c-style casts. The best practice would be to use C++ style casts like const_cast in this case instead.

The code popping up in the report:
1)
https://github.com/apache/incubator-datasketches-cpp/blob/762904bb168d44846c1fe4f178998c9a8a57ccba/common/include/serde.hpp#L53
This can be a reinterpret_cast<char*>(const_cast<T*>(items))
2)
https://github.com/apache/incubator-datasketches-cpp/blob/762904bb168d44846c1fe4f178998c9a8a57ccba/kll/include/kll_sketch_impl.hpp#L381
Note, fixing this will result that 2 lines below will pop up in the report, fixing that will reveal the same error another 2 lines below, and so on. Removing the const-ness of the local variables would solve the issue.

This ticket focuses only on the kll/ and common/ folders of the C++ library as my work was only touching those folders so I've only run the report on them. And this ticket covers only those c-style casts where the const-ness is lost during the cast

**Comment by jmalkin** [comment]
We have more of these in other sketches, but this specific issue has been resolved by that merged PR.

**Comment by leerho** [comment]
@Jon Malkin <jon.malkin@gmail.com>
If we have more of these in other sketches, can we at least create a TODO
item to track them down and fix those too?
