### ISSUE TITLE
Python wrapper doesn't work 

### ISSUE THREAD

**Issue by shrimats** [apache/incubator-datasketches-cpp#82]
Trying to use the python wrapper for datasketches-cpp to use the thetasketches.. tried pip install from git as well as using the setup script.. Get this error on importing datasketches

ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datasketches.so, 2): Symbol not found: __ZN12datasketches25update_theta_sketch_allocINSt3__19allocatorIvEEE7builder12DEFAULT_LG_KE

**Comment by jmalkin** [comment]
Interesting. I uninstalled my old library and did a clean version using pip install from git. Worked just fine for me on OS X 10.15.2 with python 3.7.

One thing I noticed is that mine installed to /usr/local/lib/python3.7/site-packages/datasketches.so but I'm not aware of having done anything special to configure that.

**Comment by shrimats** [comment]
I am trying to upgrade my OS X version.  When will this package be available on pypi? Is there a plan to do that?

**Comment by jmalkin** [comment]
We'll look at adding to pypi once we have both a "formal" release and an understanding of how to automate pushing things to pypi. Help is welcome, but closing this issue at this point.
