### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by steveatwork** [apache/incubator-datasketches-cpp#93]
Trying all the different approaches to python wrapper installation but they all seem to boil down to this error:

`incubator-datasketches-cpp/python/src/fi_wrapper.cpp:90:6: error: no matching member function for call to 'def'
    .def("merge", &frequent_items_sketch<T>::merge)`

along with a few other errors in pybind of `candidate template ignored`

What am I missing?

**Comment by jmalkin** [comment]
We added a moving merge method earlier but we don't have a CI pipeline to run the full set of tests and missed that.

Pybind is confused about which merge method to use, so need to specify one in that line. I believe that will fix it.  I dunno how fast I can get an approval on the patch but I _think_ i can get a new branch in a few minutes.

**Comment by jmalkin** [comment]
Yup, a one-line fix. Change that line to:
`.def("merge", (void (frequent_items_sketch<T>::*)(const frequent_items_sketch<T>&)) &frequent_items_sketch<T>::merge)`
and it should work. Alternatively, check out the python_fi_fix branch. Or wait until the PR is approved, which is the slowest option.

**Comment by steveatwork** [comment]
Thanks for the speedy response and fix! I really imagined that I had something misconfigured on my end because... that's usually what the trouble is.

While I'm here I also wanted to point out that in the recursive clone the pybind repo is linked with ssh which can cause a sad permission error for anyone not set up for ssh. Https links for that dependency would make it simpler, since it's a public package anyway.

**Comment by jmalkin** [comment]
@steveatwork thanks for that suggestion.

I have a branch pybind_via_https that supposedly changes the include to https. It works if I look at the .gitmodules file, anyway. But I made it a clean branch -- which means the earlier fix isn't in it since that hasn't been merged yet (pending review). I think/hope it'll all be tidied up sometime Friday, US Pacific time.

**Comment by AlexanderSaydakov** [comment]
@steveatwork The fix is in the master. Could you give it a go please? Thank you.

**Comment by steveatwork** [comment]
Tested and everything looks fine to me. Thanks!
